doc-warnings: true
test-warnings: false
strictness: high
pep8:
  full: true
autodetect: true
requirements:
  - requires/testing.txt
  - requires/installation.txt
ignore-paths:
  - docs
  - examples
  - tests
  - setup.py
python-targets:
  - 2
  - 3
