language: python
sudo: false
python:
  - 3.5
install:
 - pip install -r requires/testing.txt
script: nosetests
after_success:
 - codecov
deploy:
  distributions: bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 3.5
    tags: true
    all_branches: true
  password:
    secure: "qWT5a/SerkQv0YwggGn2gIagsLfjZsf/a6X0psuTF5nfP4QLtW0De0V87T3CG8jzmGsRCvwDuqmCcysw4aiwhOjLwIgA1DVfnhOPb3cirfxbNfRo5syUkGzc2OnDMcEBw6YHmfaudS9r7nPpXxFN2T/GongS8f/XmgFrqyew/EMJLNJKWBz4SHdAx7RCElLEJ8JQrqJm1hPu1thKrUXq2PzdJ13JEureAHNnqv6Nqf9+9l49GYZq4Dxw+Dr8C45Ve1+Wg/+e/BLce9aISlAnkgaB+xpLLFYUXI0aorqiHFqa1qDy+xjmEpJAZXES0dbHt/KrHIToE4v47tUqOif0ikE5D7ToHZeJlOP6PfbS4to0uO8US0QsNfT+ReOfZRHAnuvkuNqabzoTH2WCWPZDNMngPkKo3AulL/etm/s0bdZGUNS5dm2D2Edcgu3G8CfwdEOauiy5d9wBm/Ib+eOk++fHeDHkWoz40iwBrovFP/xXJr8hi40UxXfyKFRdeKK1aDUS7ClvYVgpLCvwx7UBPZuorMIlYQKi/hh6+IsLHA3mDqFDFWlUXZO6ZfGznvXTCF5/dvnc3DMtufvekQAdm4hxKGnxcQJTcTjTvu26VjAyjKkSW3866mAVkZflEErJQNva9IC9VewQXNV+yY+KwWd6+If2rHfBDYxemRQcIo0="
